spring:
  application:
    name: ${APPLICATION_NAME:java8-spring-boot-seed,base-bff,base-error,base-api}

keycloak:
  cors: true
  bearer-only: true
  enabled: true
  disable-trust-manager: true
  public-client: true
  principal-attribute: preferred_username

springdoc:
  swagger-ui:
    path: /
---
server:
  port: ${PORT}
  servlet:
    context-path: /bff-or-api-or-acl/${VERSION}/seed

spring:
  config:
    activate:
      on-profile: default
    import: "configserver:"
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URL}
      label: ${SPRING_CLOUD_CONFIG_LABEL}
      profile: ${SPRING_CLOUD_CONFIG_PROFILE}

keycloak:
  auth-server-url: ${access-management.auth.server.url}
  realm: ${access-management.users.realm}
  resource: mercury

rest.client.default.timeout: ${service.timeout}

seed:
  prefix: "BFF|API|ACL-SEE:"
  security-headers:
    allowed-origin:
    allowed-methods: POST,GET,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "Accept,Access-Control-Allowed-Origin,Access-Control-Allowed-Methods,\
      Access-Control-Allowed-Headers,Authorization,Content-Type,clientenv,clientname,clientver,enterpriseid"
  character-repository:
    url: ${seed.character-repository.url}
---
spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health,refresh

keycloak:
  auth-server-url: https://sso-rhsso-inte.apps.ocp-np.sis.ad.bia.itau/auth/
  realm: HomeBankingEmpresas
  resource: mercury

rest.client.default.timeout: 5000

seed:
  prefix: "BFF|API|ACL-SEE:"
  security-headers:
    allowed-origin:
    allowed-methods:
    allowed-headers:
  character-repository:
    url: https://swapi.dev/api/people/{id}/
